name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: github.repository_owner == 'OneLiteFeatherNET'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
      - name: Clean Build
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          git submodule init
          git submodule update --init
          ./gradlew applyPatches
          ./gradlew :patched-minestom:jar
      - name: Determine release status
        if: ${{ runner.os == 'Linux' }}
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
#      - name: Archive Artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: Minestom Archive
#          path: patched-minestom/build/libs/minestom-*.jar
#      - name: Publish to Github
#        run: |
#          ./gradlew :patched-minestom:publishMavenJavaPublicationToMavenRepository
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}