name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    # Run on all label events (won't be duplicated) or all push events or on PR syncs not from the same repo
    if: github.repository_owner == 'OneLiteFeatherNET'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          cache: gradle
          java-version: 17
      - name: Publish
        env:
          TAG_VERSION: ${{ github.ref_name }}
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
          echo "Version: ${TAG_VERSION}" >> $GITHUB_STEP_SUMMARY
